---
linux_arch_install_paru: true

linux_common_packages:
  - git
  - zsh
  - stow
  - fzf
  - unzip
  - curl
  - ripgrep
  - zoxide
  - duf
  - btop
  - jq
  - direnv
  - micro
  - bash-completion

linux_debian_packages:
  - build-essential
  - kitty
  - bat
  - fd-find
  - p7zip-full
  - less
  - python3-pip
  - gnupg
  - openssh-client
  - locales

linux_arch_packages:
  - base-devel
  - kitty
  - bat
  - fd
  - p7zip
  - less
  - lesspipe
  - python-pip
  - gnupg
  - openssh

linux_fedora_packages:
  - '@development-tools'
  - kitty
  - bat
  - fd-find
  - p7zip
  - p7zip-plugins
  - less
  - python3-pip
  - gnupg2
  - openssh-clients

linux_cargo_packages:
  - crate: eza
    bin: eza
  - crate: git-delta
    bin: delta
  - crate: rip2
    bin: rip
  - crate: fcp
    bin: fcp
  - crate: du-dust
    bin: dust
  - crate: tre-command
    bin: tre
  - crate: topgrade
    bin: topgrade
  - crate: hyperfine
    bin: hyperfine
  - crate: sd
    bin: sd