---
linux_nerd_font_url: "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/Monaspace.zip"
linux_bat_extras_repo: "https://github.com/eth-p/bat-extras.git"
linux_yazi_url: "https://github.com/sxyazi/yazi/releases/latest/download/yazi-x86_64-unknown-linux-gnu.zip"
linux_zellij_url: "https://github.com/zellij-org/zellij/releases/latest/download/zellij-x86_64-unknown-linux-musl.tar.gz"
linux_onefetch_url: "https://github.com/o2sh/onefetch/releases/latest/download/onefetch-linux.tar.gz"
