version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    reviewers:
      - 'DoubledDoge'
    assignees:
      - 'DoubledDoge'
    groups:
      actions-updates:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
          - 'major'
    commit-message:
      prefix: 'chore'
      