name: Dotfiles CI

on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          working_directory: ansible
          args: setup.yml
          requirements_file: requirements.yml

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './bootstrap'